### ISSUE TITLE
Not ready for showtime

### ISSUE THREAD

**Issue by Seamus** [Michael-D-Johnson/Bokeh-Map-Example#1]
There are user-specific variables that need to be reset by any user, and configuration files that are missing (app.config.from_envvar('CIVIS_CONFIG')). 

As someone unfamiliar with applications of this kind, the
     app=SQLAlchemy(app)
command looks nonsensical: databaseConnection=DBProgram(FlaskApp) ??

Needs some documentation

**Comment by Michael-D-Johnson** [comment]
Please perform a git pull. I've moved the old master to a "flask" branch and made a stripped-down example without Flask and SQLAlchemy as the new master.
